### ISSUE TITLE
KeyError: 'classifier'

### ISSUE THREAD

**Issue by biancads** [globality-corp/sklearn-hierarchical-classification#27] opened 2019-10-12 18:39 UTC
I wanted to use the HierarchicalClassifier with a RandomForestClassifier. I used the provided example.
```
X_train, X_test, y_train, y_test = train_test_split(X, y_spe, stratify=y_spe, test_size=0.2, random_state=42)
base_est = make_pipeline(RandomForestClassifier(n_estimators=100, max_features=122))
clf = HierarchicalClassifier(base_estimator=base_est,
                             class_hierarchy=hierarchy)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
```

However, i keep getting the following error:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-35-965177ad698c> in <module>()
      3                              class_hierarchy=hierarchy)
      4 clf.fit(X_train, y_train)
----> 5 y_pred = clf.predict(X_test)

~\Anaconda3\lib\site-packages\sklearn_hierarchical_classification\classifier.py in predict(self, X)
    214             return path[-1]
    215 
--> 216         y_pred = apply_along_rows(_classify, X=X)
    217         return y_pred
    218 

~\Anaconda3\lib\site-packages\sklearn_hierarchical_classification\array.py in apply_along_rows(func, X)
     29             lambda x: func(x.reshape(1, -1)),
     30             axis=1,
---> 31             arr=X,
     32         )
     33 

~\Anaconda3\lib\site-packages\numpy\ma\extras.py in apply_along_axis(func1d, axis, arr, *args, **kwargs)
    391     outshape = np.asarray(arr.shape).take(indlist)
    392     i.put(indlist, ind)
--> 393     res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
    394     #  if res is a number, then we have a smaller output array
    395     asscalar = np.isscalar(res)

~\Anaconda3\lib\site-packages\sklearn_hierarchical_classification\array.py in <lambda>(x)
     27         #   https://github.com/numpy/numpy/issues/8352
     28         return np.ma.apply_along_axis(
---> 29             lambda x: func(x.reshape(1, -1)),
     30             axis=1,
     31             arr=X,

~\Anaconda3\lib\site-packages\sklearn_hierarchical_classification\classifier.py in _classify(x)
    211         def _classify(x):
    212             # TODO support multi-label / paths?
--> 213             path, _ = self._recursive_predict(x, root=self.root)
    214             return path[-1]
    215 

~\Anaconda3\lib\site-packages\sklearn_hierarchical_classification\classifier.py in _recursive_predict(self, x, root)
    424 
    425     def _recursive_predict(self, x, root):
--> 426         clf = self.graph_.node[root][CLASSIFIER]
    427         path = [root]
    428         path_proba = []

KeyError: 'classifier'
```

**Comment by adamhadani** [comment] 2020-01-09 14:53
@biancads  - thanks for reporting. for completeness and so I can try and reproduce, do you mind sharing some (X, y) values I can use to reproduce this?

**Comment by adamhadani** [comment] 2020-01-09 15:27
@biancads - I was not able to reproduce your issue with latest version of code (there's been a couple of new releases since you reported this so very possible fixed as side-effect of another bug I addressed).

For reference here is the example I used. I will close this issue for now, feel free to re-open with more specific details on how to reproduce:

```python
import networkx as nx
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier

from sklearn_hierarchical_classification.classifier import HierarchicalClassifier
from sklearn_hierarchical_classification.constants import ROOT

# generate some class hierarchy
def create_graph(root=ROOT):
    # simple clothing hierarchy
    G = nx.DiGraph()
 
    G.add_nodes_from([root, "Mens", ])
    G.add_edge(root, "Mens")
    G.add_edge("Mens", "Shirts")
    G.add_edge("Mens", "Bottoms")
    G.add_edge("Mens", "Jackets")
    G.add_edge("Mens", "Swim")
    return G

G = create_graph(ROOT)

# generate some data
np.random.choice(1235)
categories = list(G.nodes())
categories.remove(ROOT)
y = np.random.choice(categories, size=50)

# make sure all nodes were selected
assert set(y) == set(categories)
X = np.random.normal(size=(len(y), 10))

# create training/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

# train classifier
base_estimator = make_pipeline(
    RandomForestClassifier(n_estimators=100, max_features=len(set(y)))
)
clf = HierarchicalClassifier(
    base_estimator=base_estimator,
    class_hierarchy=G,
)
clf.fit(X_train, y_train)

# try and predict
y_pred = clf.predict(X_test)
```

**Closed by adamhadani** 2020-01-09 15:27 UTC

**Comment by yashmehta10** [comment] 2021-05-31 01:04
Hey, I'm facing the same issue. I am using SVM as the classifier.  
![image](https://user-images.githubusercontent.com/17799552/120126520-e05dd880-c1ff-11eb-8751-c572be18dcec.png)

The fit is completed but some nodes are terminated due to lack of data, can this be the reason?
![image](https://user-images.githubusercontent.com/17799552/120126384-6decf880-c1ff-11eb-94ee-37a59e7934b8.png)


Unfortunately I wont be able to provide the data. 

Thank you.
