### ISSUE TITLE
List of lists issue in multi_labeled

### ISSUE THREAD

**Issue by nilunima** [globality-corp/sklearn-hierarchical-classification#25] opened 2019-09-19 16:26 UTC
Hi,

I just wanted to apply your h_fbeta_score to a hierarchical problem of mine. I believe there is a bug in the metrics.py line 55 onwards. MultiLabelBinarizer takes an iterable of iterables into its functions e.g. fit and transform. Looking at your comment in line 55 you also noticed that and then simply put the entire list into another list to solve the problem. I believe you have to put every element in y_true and y_pred into its own list, so you will end up with an actual list of list. 

Your classify_digits example works either way, but only because every element is of length 1. My labels are longer words, so the transformation produced a bad output. I tried doing exactly what I described above, the result of your example is still the same and it now also works for longer words as labels.

No exactly the same issue, but similar, see: https://stackoverflow.com/questions/57917936/multilabelbinarizer-gives-individual-characters-instead-of-the-classes 

Best regards

**Comment by adamhadani** [comment] 2019-09-25 23:51
@nilunima thanks for detailed report! any chance you can try your hand at a PR for contributing a fix? ideally with an added unit-test example to ensure behavior works as expected? otherwise, might take me a bit of time to get to it, but will do my best to get on it promptly!

**Comment by adamhadani** [comment] 2020-01-08 20:04
@nilunima - I could not reproduce this issue, and you haven't provided any specific code example so i'm going to close this. I did beef up metrics unit-tests and added a couple test cases to specifically test for using string literals - please see https://github.com/globality-corp/sklearn-hierarchical-classification/pull/34/files#r364418588 and feel free to open a new ticket with more details if issue persists.

**Closed by adamhadani** 2020-01-08 20:04 UTC
Labels: bug
